// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_JNUFzxEO6cFB9AjGPs7UnGgJIUA0nxU',
    appId: '1:1028628249874:web:89a664864da483b64647cb',
    messagingSenderId: '1028628249874',
    projectId: 'muslim-way-a50ab',
    authDomain: 'muslim-way-a50ab.firebaseapp.com',
    storageBucket: 'muslim-way-a50ab.firebasestorage.app',
    measurementId: 'G-97HJTBV738',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKXTlBMOldiZH5LVO34gV9lIGn39Lb2hw',
    appId: '1:1028628249874:android:bf336f57579df0934647cb',
    messagingSenderId: '1028628249874',
    projectId: 'muslim-way-a50ab',
    storageBucket: 'muslim-way-a50ab.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVL7Pl4BsUXNB-xdQuv5HAzUjV1mnlQHk',
    appId: '1:1028628249874:ios:ff76f5f60a8df05e4647cb',
    messagingSenderId: '1028628249874',
    projectId: 'muslim-way-a50ab',
    storageBucket: 'muslim-way-a50ab.firebasestorage.app',
    iosBundleId: 'com.example.muslimWay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_JNUFzxEO6cFB9AjGPs7UnGgJIUA0nxU',
    appId: '1:1028628249874:web:653ff1df579aa5194647cb',
    messagingSenderId: '1028628249874',
    projectId: 'muslim-way-a50ab',
    authDomain: 'muslim-way-a50ab.firebaseapp.com',
    storageBucket: 'muslim-way-a50ab.firebasestorage.app',
    measurementId: 'G-QP0EVMFYYF',
  );
}
